#!/bin/bash
DEFAULT_URL=/var/dbase/tess.db
DATABASE=${1:-${DEFAULT_URL}}
SECS=3
FILES=$(ls -1 sql/*.sql)

read -p "This is the SQLite3 database path ([Ctrl-C] to abort): ${DATABASE}" yes_no

if [ "$?" -ne "0" ]; then
	echo "No SQL Files to process. Exiting."
	exit 0
fi

if ! test -d sql/processed; then
  mkdir -p sql/processed
fi

for FILE in $FILES
do
	echo "sqlite3 ${DATABASE} < ${FILE}"
	/usr/bin/time --format='%C took %e seconds' sqlite3 ${DATABASE} < ${FILE}
	mv ${FILE} sql/processed || exit 255
	echo "pausing for ${SECS} seconds. ([Ctrl-C] to abort)"
	sleep ${SECS}
done

echo "Processing database ${DATABASE} ended!"
